### ISSUE TITLE
question

### ISSUE THREAD

**Issue by thedreamgirl** [dialdroid-android/DIALDroid#2]
Can I build the project in Eclipse instead of Ant ?

**Comment by amiangshu** [comment]
Yes, you can. Eclipse comes with ant. Right click on the build.xml and select run as ant build.

**Comment by thedreamgirl** [comment]
I have imported the project into Eclipse by this way :


 File-->New--->project--->Java Project From Existing Ant BuildFile 

But after importing into eclipse, I can see only src folder and build.xml and referenced libraries folder. I could not see other folders inside eclipse (such as build folder).

What I need to do to see all the folders? 

Please help me.

Thanks!
